#                            _
#  _ __ ___ _ __   ___  __ _| |_ ___ _ __
# | '__/ _ \ '_ \ / _ \/ _` | __/ _ \ '__|
# | | |  __/ |_) |  __/ (_| | ||  __/ |
# |_|  \___| .__/ \___|\__,_|\__\___|_|
#          |_|
#
#  https://github.com/rocats/repeater-v2
#
#  Copyright (C) 2023 @yqlbu
#
#  This is a self-hosted software, liscensed under the MIT License.
#  See /License for more information.

---
name: Build OCI Container (PR)
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  # Pre-Action Stage
  pre-actions:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/pre-actions.yml@master
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.pull_request.head.sha }}
      fetch-depth: 0
    secrets: inherit

  # Build Stage
  build-and-push:
    runs-on: ubuntu-latest
    needs: [pre-actions]
    env:
      dockerfile: Dockerfile
      image_tag: pr-${{ needs.pre-actions.outputs.git_sha_short }}-${{ github.run_number }}
    outputs:
      image_tag: ${{ env.image_tag }}
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build - quay.io
        id: quay_build
        uses: aevea/action-kaniko@master
        with:
          registry: quay.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.QUAY_PASS }}
          image: ${{ github.repository }}
          build_file: ${{ env.dockerfile }}
          tag: ${{ env.image_tag }}
          tag_with_latest: true
          cache: true
          cache_registry: quay.io/${{ github.repository_owner }}/cache

      - name: Echo image uri
        run: |
          echo "ImageURI (quay.io): quay.io/${{ github.repository }}:${{ env.image_tag }}"

  post-actions:
    needs: [pre-actions,build-and-push]
    uses: daeuniverse/ci-seed-jobs/.github/workflows/post-actions.yml@master
    with:
      image_tag: ${{ needs.build-and-push.outputs.image_tag }}
      sha_short: ${{ needs.pre-actions.outputs.git_sha_short }}
    secrets: inherit
